### PR TITLE
Update UI group list to use QTableView

### PR DESCRIPTION
**Pull request by tsalemink**
This PR reworks the way the UI displays the list of groups and their associated widgets (check-box, push-button, etc.). These item are now displayed using QTableView, QAbstractTableModel and QStyledItemDelegate subclasses, adhering to the Qt model/view architecture.

An attempt has been made at enabling internal drag-drop functionality for the QTableView items.

### CODE REVIEW

**Comment by hsorby** [comment]
I have a working table model for the groups but I think there is a bug in Zinc with regards to the graphic ordering. I will need to speak with Richard about this to confirm.  Whilst graphics are getting re-ordered the are not going into the correct order which results in a mismatch between expected graphic ordering and actual graphic ordering.

**Comment by hsorby** [comment]
I think we can merge this one in now.  I find that it is working as expected for me.

**Comment by hsorby** [comment]
This should be ready to go now? Is there anything missing? I cannot think of anything more to add to complete this PR.

**Comment by tsalemink** [comment]
Yes, it all looks good to me.

**Review by hsorby — APPROVED** [review]

**Pull request merged**
